baseURL = 'https://koprecel.github.io/'
title = "Min's Learning Den"
languageCode = 'en-us'
theme = "PaperMod"
paginate = 5000 # frontpage pagination
copyright = "Copyright 2022 © Min Dye. All rights reserved."
enableEmoji = true # https://www.webfx.com/tools/emoji-cheat-sheet/
googleAnalytics = "G-SCM5JE3TQ5"

[params]
    env = "production"
    SEOTitle = "Min Dye Blog"
    keyword = "Min, Dye, Software, Python"
    sidebar_about_description = "test sidebar description"

[markup.goldmark.renderer]
    unsafe = true

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "github"
name = "Min's GitHub"
url = "https://github.com/KoPrecel"
weight = 30

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 40

[outputs]
home = [ "HTML", "RSS", "JSON" ]
