baseURL = 'https://koprecel.github.io/'
title = "Min's Learning Den"
languageCode = 'en-us'
theme = "PaperMod"
paginate = 5000 # frontpage pagination
copyright = "Copyright 2022 © Min Dye. All rights reserved."
enableEmoji = true # https://www.webfx.com/tools/emoji-cheat-sheet/
googleAnalytics = "G-SCM5JE3TQ5"

[params]
    env = "production"
    SEOTitle = "Min Dye Blog"
    keyword = "Min, Dye, Software, Python"
    sidebar_about_description = "test sidebar description"
