baseURL = 'https://koprecel.github.io/'
title = "Min's Learning Den"
languageCode = 'en-us'
theme = "PaperMod"
paginate = 5000 # frontpage pagination
copyright = "Copyright 2022 © Min Dye. All rights reserved."
enableEmoji = true # https://www.webfx.com/tools/emoji-cheat-sheet/
googleAnalytics = "G-SCM5JE3TQ5"

[params]
    env = "production"
    SEOTitle = "Min Dye Blog"
    keyword = "Min, Dye, Software, Python"
    sidebar_about_description = "test sidebar description"

[params.homeInfoParams]
Title = "Welcome to the Den!"
Content = "Hi, my name is Min :) This blog is an archive of things I learned along my programming journey, as well as things that make me grow as a person. Created in August of 2022, I am hoping to use this blog to enhance my studying as well as to organize a portfolio. In any case, I hope you enjoy your time here and learn things with me!"

[[params.socialIcons]]
name = "GitHub"
link = "https://github.com/KoPrecel"

[markup.goldmark.renderer]
    unsafe = true

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 30

[outputs]
home = [ "HTML", "RSS", "JSON" ]
